use super::prelude::*;
use super::{images::ImageLoader, runtime::BackendRuntime};

pub(crate) struct UiState {
    pub(crate) runtime: Rc<BackendRuntime>,
    pub(crate) window: adw::ApplicationWindow,
    pub(crate) stack: adw::ViewStack,
    pub(crate) navigation: adw::NavigationView,
    pub(crate) toast: adw::ToastOverlay,
    pub(crate) images: ImageLoader,
    pub(crate) snapshot: RefCell<BackendSnapshot>,
    pub(crate) home: gtk::Box,
    pub(crate) discover: gtk::Box,
    pub(crate) library: gtk::Box,
    pub(crate) search: gtk::Box,
    pub(crate) downloads: gtk::Box,
    pub(crate) insights: gtk::Box,
    pub(crate) settings: gtk::Box,
    pub(crate) search_entry: gtk::SearchEntry,
    pub(crate) search_list: RefCell<Option<gtk::ListBox>>,
    pub(crate) search_results: RefCell<Vec<FrontendSubject>>,
    pub(crate) search_online: RefCell<Vec<FrontendSubject>>,
    pub(crate) search_error: RefCell<Option<String>>,
    pub(crate) search_generation: Cell<u64>,
    pub(crate) home_feed: RefCell<Option<HomeFeedResponse>>,
    pub(crate) home_feed_requested: Cell<bool>,
    pub(crate) home_feed_error: RefCell<Option<String>>,
    pub(crate) discovery_feed: RefCell<Option<DiscoveryFeedResponse>>,
    pub(crate) discovery_requested: Cell<bool>,
    pub(crate) discovery_feed_error: RefCell<Option<String>>,
    pub(crate) downloads_data: RefCell<Option<DownloadTasksResponse>>,
    pub(crate) downloads_requested: Cell<bool>,
    pub(crate) downloads_error: RefCell<Option<String>>,
    pub(crate) insights_data: RefCell<Option<InsightsDashboardResponse>>,
    pub(crate) insights_requested: Cell<bool>,
    pub(crate) insights_error: RefCell<Option<String>>,
    pub(crate) insight_range: Cell<InsightRange>,
    pub(crate) library_grid: Cell<bool>,
    pub(crate) library_cloud: Cell<bool>,
    pub(crate) library_sort: Cell<u32>,
    pub(crate) logs: RefCell<Vec<String>>,
    pub(crate) scan_message: RefCell<String>,
    pub(crate) scan_fraction: Cell<f64>,
    pub(crate) sync_message: RefCell<String>,
    pub(crate) sync_fraction: Cell<f64>,
    pub(crate) sync_loading: Cell<bool>,
    pub(crate) snapshot_loading: Cell<bool>,
    pub(crate) scan_loading: Cell<bool>,
    pub(crate) settings_dirty: Cell<bool>,
    pub(crate) settings_save_generation: Cell<u64>,
    pub(crate) settings_save_in_flight: Cell<bool>,
    pub(crate) settings_data: RefCell<Option<FrontendEditableSettings>>,
    pub(crate) settings_requested: Cell<bool>,
    pub(crate) settings_error: RefCell<Option<String>>,
    pub(crate) detail_dynamic_refreshes: RefCell<HashMap<String, Instant>>,
    pub(crate) detail_dynamic_in_flight: RefCell<HashSet<String>>,
    pub(crate) settings_form: RefCell<Option<Rc<SettingsForm>>>,
    pub(crate) next_page_id: Cell<u64>,
}

pub(crate) struct SettingsForm {
    pub(crate) base: FrontendEditableSettings,
    pub(crate) media_libraries: Rc<RefCell<Vec<String>>>,
    pub(crate) controls: RefCell<HashMap<String, gtk::Widget>>,
    pub(crate) secret_values: RefCell<HashMap<String, String>>,
    pub(crate) media_group: adw::PreferencesGroup,
}

pub(crate) fn empty_snapshot() -> BackendSnapshot {
    BackendSnapshot {
        subjects: Vec::new(),
        bangumi_collections: Vec::new(),
        bangumi_auth: BangumiAuthStatusData {
            configured: false,
            authenticated: false,
            username: None,
            nickname: None,
            avatar_url: None,
            client_configured: false,
            redirect_uri: String::new(),
            pending_sync_count: 0,
            last_error: None,
        },
        stats: crate::backend_api::LibraryStats {
            total: 0,
            matched: 0,
            unmatched: 0,
            tentative: 0,
        },
        settings: crate::backend_api::FrontendSettings {
            bangumi_enabled: false,
            bangumi_auto_match: false,
            bangumi_cache_images: false,
            dandanplay_configured: false,
        },
    }
}
